CREATE TABLE produtos(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    preco NUMBER (10,2) NOT NULL CHECK(preco > 0),
    quantidade_estoque NUMBER(10) DEFAULT 0 NOT NULL CHECK(quantidade_estoque >= 0),
    status CHAR(1) DEFAULT 'A' CHECK(status IN ('A','I')),
    data_cadastro DATE DEFAULT SYSDATE

);

